Repository Kelompok-1-Capstone-Alterra/backend-golang, pull requests merged in 2023-06, with the labels that each got.

#16 New feature : Mobile - Get Weather
  config/config.go
  controller/user/explore_monitoring_controller.go
  model/user.go
  route/route.go
  utils/jwt.go
Labels: enhancement

#20 belum jadi
  controller/user/explore_monitoring_controller.go
  route/route.go
Labels: fix

#22 Development
  assets/images/b139e4df-2dc7-41e1-94f8-5db6c0b1bb73.png
  assets/images/fdd2be80-6552-412c-8e73-355bddb415b8.png
  config/config.go
  controller/global_controller.go
  controller/user/explore_monitoring_controller.go
  model/user.go
  route/route.go
  utils/jwt.go
Labels: enhancement

#17 New Feature : Mobile - Check email valid
  controller/user/membership_controller.go
  route/route.go
Labels: enhancement

#18 New Feature : Mobile - Reset password
  controller/user/membership_controller.go
  route/route.go
Labels: enhancement

#23 New Feature : Mobile - Get weather article
  controller/user/explore_monitoring_controller.go
  model/admin.go
Labels: enhancement

#27 Fix/mobile/membership
  controller/user/membership_controller.go
  go.mod
  go.sum
  model/user.go
  utils/email_validation.go
Labels: fix

#30 change to GET method
  route/route.go
Labels: fix

#31 fix testing from QA
  controller/user/membership_controller.go
  model/user.go
Labels: fix

#32 Development
  controller/user/membership_controller.go
  model/user.go
Labels: fix

#33 fix password min and max length
  controller/user/membership_controller.go
Labels: fix

#35 done fixing
  controller/user/membership_controller.go
  route/route.go
Labels: fix

#36 done fixing
  controller/user/explore_monitoring_controller.go
  model/admin.go
  model/user.go
Labels: fix

#29 Product Recomendation : Mobile - DONE
  controller/user/recomendation_controller.go
  model/admin.go
  model/user.go
  route/route.go
Labels: enhancement

#38 add cors
  route/route.go
Labels: enhancement

#40 New Feature : Web Plant CRUD DONE
  config/config.go
  controller/admin/plant_page_controller.go
  model/admin.go
  route/route.go
  utils/jwt.go
Labels: enhancement

#45 Mobile/get search plant available detail
  assets/images/52e3edec-4066-45dd-a3a9-f2bc41f2941c.png
  assets/images/615885dd-0af7-4932-b5ba-6e0dda64698b.png
  assets/images/905c1a35-4f00-45d0-9c6f-55d547ca4f4f.png
  config/config.go
  controller/user/explore_monitoring_controller.go
  model/admin.go
  model/user.go
  route/route.go
Labels: enhancement

#50 Mobile : API - GetWateringArticle & GetTemperatureArticle
  controller/user/explore_monitoring_controller.go
  route/route.go
Labels: enhancement

#52 Mobile/start planting
  assets/images/dummy.png
  assets/images/fdd2be80-6552-412c-8e73-355bddb415b8.png
  config/config.go
  controller/user/explore_monitoring_controller.go
  model/admin.go
  model/user.go
  route/route.go
Labels: enhancement

#53 Web/overview
  controller/admin/landing_page_controller.go
  controller/user/explore_monitoring_controller.go
  model/user.go
  route/route.go
Labels: enhancement

#61 done fixing
  controller/user/explore_monitoring_controller.go
Labels: fix

#63 New Feature : Mobile - Settings
  config/config.go
  controller/user/setting_controller.go
  model/user.go
  route/route.go
Labels: enhancement

#64 Fix - Update Plant
  controller/admin/plant_page_controller.go
  controller/user/setting_controller.go
  model/admin.go
Labels: fix

#41 Mobile/articles
  config/config.go
  controller/user/articles.go
  model/user.go
  route/route.go
Labels: enhancement

#65 DONE : button dead & harvest, temperature alert
  controller/user/explore_monitoring_controller.go
Labels: fix

#75 Global/render template
  controller/global_controller.go
  controller/show_all_db.go
  controller/user/articles.go
  controller/user/explore_monitoring_controller.go
  controller/user/setting_controller.go
  model/user.go
  route/route.go
  templates/index.html
  templates/index_admins.html
  templates/index_myplants.html
  templates/index_plants.html
  templates/index_users.html
Labels: enhancement

#77 Mobile - Get Weathers : get country name in response body
  controller/user/explore_monitoring_controller.go
  go.mod
  go.sum
Labels: fix

#68 menambahkan myplant_controller
  controller/user/articles.go
  controller/user/myplants_controller.go
  route/route.go
Labels: enhancement

#74 New Feature : Web - Suggestions
  controller/admin/suggestion_page_controller.go
  route/route.go
Labels: enhancement

#81 Bug report qa testcase/login admin
  controller/admin/landing_page_controller.go
Labels: bug

#85 done fixing with major update
  controller/user/explore_monitoring_controller.go
  controller/user/membership_controller.go
  model/user.go
  route/route.go
Labels: fix

#83 New feature : Mobile - Get MyPlant Name & Change MyPlant Name
  controller/user/explore_monitoring_controller.go
  route/route.go
Labels: enhancement

#87 Fix - Web Suggestions
  controller/admin/suggestion_page_controller.go
Labels: fix

#88 Fix/mobile minor
  controller/admin/plant_page_controller.go
  controller/user/articles_controller.go
  controller/user/explore_monitoring_controller.go
  controller/user/membership_controller.go
  controller/user/myplants_controller.go
Labels: fix

#91 Mobile/recomendation/create product
  controller/admin/product_page_controller.go
  controller/user/recomendation_controller.go
  route/route.go
  utils/phone_validation.go
Labels: fix

#94 Fix - Settings
  controller/user/setting_controller.go
Labels: fix

#96 Fix/mobile/timezone
  controller/admin/article_page_contoller.go
  controller/admin/plant_page_controller.go
  controller/admin/product_page_controller.go
  controller/user/explore_monitoring_controller.go
  controller/user/myplants_controller.go
  controller/user/recomendation_controller.go
Labels: fix

#98 Fix - Web Suggestions
  controller/admin/suggestion_page_controller.go
Labels: fix

#103 Fix - Mobile Settings
  controller/admin/suggestion_page_controller.go
  controller/user/setting_controller.go
  model/user.go
Labels: fix

#105 Fix/mobile/widho pt2
  controller/user/articles_controller.go
  controller/user/explore_monitoring_controller.go
  controller/user/myplants_controller.go
Labels: fix

#107 Fix - Mobile Settings
  controller/user/setting_controller.go
  go.mod
  go.sum
  model/user.go
Labels: fix

#109 crete upadted_at DESC condition
  config/config.go
  controller/admin/article_page_contoller.go
  controller/admin/landing_page_controller.go
  controller/admin/plant_page_controller.go
  controller/admin/product_page_controller.go
  controller/admin/suggestion_page_controller.go
Labels: fix

#111 Global controller
  capstonealterra-0457bfb5b315.json
  controller/global_controller.go
  go.mod
  go.sum
Labels: enhancement

#116 fix/globalController : Err msg
  controller/global_controller.go
Labels: fix

#118 Fix - Update Plant
  controller/admin/plant_page_controller.go
  controller/user/setting_controller.go
Labels: fix

#119 done fixing
  controller/admin/plant_page_controller.go
  controller/show_all_db.go
  templates/index.html
  templates/index_users.html
Labels: fix

#122 Fix/admin/everview
  controller/admin/landing_page_controller.go
Labels: fix

#123 Fix : Admin Overview Data
  controller/admin/landing_page_controller.go
Labels: fix

#125 Fix/mobile/article
  controller/user/articles_controller.go
  route/route.go
Labels: fix

#126 Development
  controller/user/articles_controller.go
  route/route.go
Labels: fix

#129 fix : LIMIT query command for weatherData
  controller/admin/landing_page_controller.go
Labels: fix

#130 Development
  controller/admin/landing_page_controller.go
Labels: fix

#131 fix : article addLIKE & DeleteLIKE logic
  controller/user/articles_controller.go
Labels: fix

#132 Development
  controller/user/articles_controller.go
Labels: fix

#134 TestID : A-S-11 Done
  controller/user/setting_controller.go
Labels: fix

#135 Bug report qa testcase/update profile picture
  controller/user/setting_controller.go
Labels: fix

#136 fix : overview - QUERY get the newest data from both creatted and upd…
  controller/admin/landing_page_controller.go
Labels: fix

#137 Development
  controller/admin/landing_page_controller.go
  controller/global_controller.go
  controller/user/explore_monitoring_controller.go
  controller/user/setting_controller.go
Labels: fix
